sudo: required
services:
    - docker

before_install:
    - docker build -t ranjanray/docker-react -f DockerFile.dev .

script:
    - docker run -e CI=true ranjanray/docker-react npm run test -- --coverage